Day 5: React - Introduction to State
AnimeshKumarSuccessive/react-client pull request #5
Opened 2021-10-13 18:45 UTC by AnimeshKumarSuccessive

Animesh Kumar
Ticket number: [40431](https://redmine.successive.tech/issues/40431)

2021-10-26 13:14 UTC, yogeshsinghh requested changes

2021-10-26 13:14 UTC, yogeshsinghh commented on src/components/Slider/Slider.jsx
> +        setIndex((i) => getNextRoundRobin(MAX_NUMBER, i));
Use banners length as the max number

2021-10-26 13:14 UTC, yogeshsinghh commented on src/components/Slider/Slider.jsx
> +        <img src={banners[index] ? banners[index] : defaultBanner} alt={altText} height={height} />
import Public folder path value and use for the image src path with the banners[index]

2021-10-26 13:14 UTC, yogeshsinghh commented on src/components/Slider/Slider.jsx
> +  defaultBanner: PropTypes.string.isRequired,
Use dafault values of the props

2021-10-26 13:14 UTC, yogeshsinghh commented on src/pages/TextFieldDemo/TextFieldDemo.jsx
> +  ];
move this array to constant file  as array of name of images  ex ["cloud.jpg", ....]

2021-10-26 13:14 UTC, yogeshsinghh commented on src/pages/TextFieldDemo/TextFieldDemo.jsx
> +        <Slider altText="Image not found" banners={images} defaultBanner={DEFAULT_BANNER_IMAGE} duration={2000} height={200} random={5} />
send random as the boolean

2021-10-27 12:10 UTC, AnimeshKumarSuccessive commented on src/pages/TextFieldDemo/TextFieldDemo.jsx
> +        <Slider altText="Image not found" banners={images} defaultBanner={DEFAULT_BANNER_IMAGE} duration={2000} height={200} random={5} />
Done

2021-10-27 14:11 UTC, AnimeshKumarSuccessive commented on src/components/Slider/Slider.jsx
> +  defaultBanner: PropTypes.string.isRequired,
Done

2021-10-28 02:22 UTC, AnimeshKumarSuccessive commented on src/pages/TextFieldDemo/TextFieldDemo.jsx
> +  ];
Done

2021-10-28 02:45 UTC, AnimeshKumarSuccessive commented on src/components/Slider/Slider.jsx
> +        setIndex((i) => getNextRoundRobin(MAX_NUMBER, i));
Done

2021-10-29 07:21 UTC, yogeshsinghh approved these changes

2021-10-29 07:21 UTC, merged