Day 6 - React - Controlled Inputs
AnimeshKumarSuccessive/react-client pull request #6
Opened 2021-10-18 13:02 UTC by AnimeshKumarSuccessive

Animesh Kumar
ticket number ; [40535](https://redmine.successive.tech/issues/40535)

2021-11-02 07:52 UTC, yogeshsinghh requested changes

2021-11-02 07:52 UTC, yogeshsinghh commented on src/App.jsx
> +      {/* <TextFieldDemo /> */}
remove commented code

2021-11-02 07:52 UTC, yogeshsinghh commented on src/components/RadioGroup/RadioGroup.jsx
> +    value,
rename value as selectedValue instead from the options

2021-11-02 07:52 UTC, yogeshsinghh commented on src/components/RadioGroup/RadioGroup.jsx
> +          ) : ''}
move this block to inputDemo.js as this component should be generic

2021-11-02 07:52 UTC, yogeshsinghh commented on src/components/RadioGroup/RadioGroup.jsx
> +          if (selectValue !== value) return false;
remove this condition and pass only those options on the basis of selected sport

2021-11-02 07:52 UTC, yogeshsinghh commented on src/components/SelectField/SelectField.jsx
> +      </div>
move this block to inputDemo.js as this component should be generic

2021-11-02 07:52 UTC, yogeshsinghh commented on src/config/constant.js
> +    value: 'cricket',
radio options values should be unique

2021-11-02 07:52 UTC, yogeshsinghh commented on src/pages/InputDemo/InputDemo.jsx
> +    });
use spread operator

2021-11-02 07:52 UTC, yogeshsinghh commented on src/pages/InputDemo/InputDemo.jsx
> +      football: value.sport && value.sport === 'football' ? event.target.attributes.label.value : '',
set value from  the event.target.value

2021-11-02 09:39 UTC, AnimeshKumarSuccessive commented on src/App.jsx
> +      {/* <TextFieldDemo /> */}
Done

2021-11-09 10:07 UTC, AnimeshKumarSuccessive commented on src/components/RadioGroup/RadioGroup.jsx
> +    value,
Done

2021-11-09 10:07 UTC, AnimeshKumarSuccessive commented on src/components/RadioGroup/RadioGroup.jsx
> +          ) : ''}
Done

2021-11-09 10:07 UTC, AnimeshKumarSuccessive commented on src/components/SelectField/SelectField.jsx
> +      </div>
Done

2021-11-09 10:07 UTC, AnimeshKumarSuccessive commented on src/config/constant.js
> +    value: 'cricket',
Done

2021-11-09 10:56 UTC, AnimeshKumarSuccessive commented on src/components/RadioGroup/RadioGroup.jsx
> +          if (selectValue !== value) return false;
Done

2021-11-10 07:39 UTC, AnimeshKumarSuccessive commented on src/pages/InputDemo/InputDemo.jsx
> +      football: value.sport && value.sport === 'football' ? event.target.attributes.label.value : '',
done

2021-11-10 07:45 UTC, yogeshsinghh approved these changes

2021-11-10 07:45 UTC, merged